# Generated by Django 5.0.6 on 2024-10-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_address_customer_age_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='firstname',
            field=models.CharField(default='first name', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default='last name', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
