# Generated by Django 5.0.6 on 2024-10-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_firstname_customer_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(default='hello', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default='hello', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(default='hello', upload_to='images/'),
        ),
    ]
